//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro1.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro2.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro3.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro4.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro5.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro6.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro7.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro8.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro9.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro10.getText());
//        board.setContents((Transferable) selection, selection);
//Clipboard board = Toolkit.getDefaultToolkit().getSystemClipboard();
//        ClipboardOwner selection = new StringSelection(jTextField9Filtro11.getText());
//        board.setContents((Transferable) selection, selection);